import React, { useState } from "react";
import { Card, CardContent } from "./ui/card";
import { Minus, Plus } from "lucide-react";

const FAQSection = () => {
  const [openItems, setOpenItems] = useState<number[]>([]);
  const [showAll, setShowAll] = useState(false);

  const toggleItem = (index: number) => {
    setOpenItems((prev) =>
      prev.includes(index) ? prev.filter((i) => i !== index) : [...prev, index]
    );
  };

  const faqs = [
    {
      question:
        "What is a Statement of Purpose (SOP) and why is it crucial for my application?",
      answer:
        "A Statement of Purpose is a personalized essay that explains your academic background, career goals, and reasons for choosing a specific program. It's crucial because it's the only subjective part of your application that allows admissions committees to understand your personality, motivations, and potential fit for their program. While grades and test scores are objective, your SOP tells your unique story and can compensate for weaker academic profiles by highlighting your aspirations and experiences.",
      highlight: true,
    },
    {
      question: "Is the SOP generated by AI?",
      answer:
        "No. Experienced human writers handcraft every SOP, using only the answers you provide. We never use automated AI tools.",
    },
    {
      question: "How does an SOP impact my chances of admission?",
      answer:
        "An SOP significantly impacts admission decisions as it demonstrates your communication skills, commitment to the field, and alignment with the program's objectives. It helps distinguish you from thousands of other applicants with similar academic credentials. A compelling SOP can be the deciding factor that gets you accepted, especially for competitive programs where multiple candidates have similar qualifications.",
      highlight: true,
    },
    {
      question: "What should I include in my SOP?",
      answer:
        "Your SOP should include: your academic background and achievements, relevant professional experience, specific reasons for choosing the program and university, short-term and long-term career goals, key projects or research experiences, and what unique value you'll bring to the program. Structure it with a compelling introduction, detailed body paragraphs covering your journey, and a strong conclusion linking everything to your future aspirations.",
    },
    {
      question: "How long should my SOP be?",
      answer:
        "Most universities require SOPs between 800-1000 words, typically 2 pages double-spaced. However, always check specific university requirements as some may have different word limits. Focus on being concise while covering all essential points - quality matters more than quantity.",
    },
    {
      question: "What are the most common SOP mistakes I should avoid?",
      answer:
        "Avoid these critical mistakes: using generic templates instead of personalizing your SOP, being dishonest or exaggerating achievements, focusing only on past accomplishments without connecting them to future goals, writing in an informal tone or using slang, submitting without thorough proofreading, failing to research the specific program and university, being too vague about your career objectives, and not following the university's specific guidelines and format requirements.",
    },
    {
      question: "How do I make my SOP stand out from other applicants?",
      answer:
        "Make your SOP unique by: sharing specific experiences that shaped your career interests, demonstrating genuine passion for your chosen field, showing deep research about the program and mentioning specific faculty or resources, connecting your past experiences logically to your future goals, using concrete examples with measurable results, and maintaining authenticity while avoiding clichés. Your personal story and genuine motivation should shine through.",
    },
    {
      question: "Should I mention my weaknesses or low grades in my SOP?",
      answer:
        "If you have significant academic weaknesses or gaps, address them briefly and honestly, but focus on what you learned from these experiences and how you've grown. Don't dwell on negatives - instead, emphasize your current readiness and commitment. Show how your experiences, even challenging ones, have prepared you for graduate studies.",
    },
    {
      question: "How specific should I be about the university and program?",
      answer:
        "Be very specific! Research the program thoroughly and mention particular faculty members whose research aligns with your interests, unique resources or labs you want to access, specific courses that excite you, and how the program's philosophy matches your goals. This shows genuine interest and helps admissions committees see you as a serious candidate who has done their homework.",
    },
    {
      question: "Can I use the same SOP for multiple universities?",
      answer:
        "Never use the exact same SOP for different universities. While you can keep the core structure and personal experiences consistent, always customize each SOP to reflect why you're specifically interested in that particular program and institution. Mention specific faculty, resources, and opportunities unique to each university.",
    },
    {
      question: "What tone should I maintain in my SOP?",
      answer:
        "Maintain a professional yet personal tone. Be formal but not overly academic or dry. Show enthusiasm and passion while remaining respectful and mature. Write in the active voice, use clear and concise language, avoid jargon unless necessary, and ensure your personality comes through while maintaining academic professionalism.",
    },
    {
      question: "How important is the opening paragraph of my SOP?",
      answer:
        "The opening paragraph is extremely important as it sets the first impression and determines whether the admissions committee will read your SOP with interest. Start with a compelling hook - perhaps a meaningful experience, defining moment, or clear statement of your goals. Avoid generic openings like 'I have always been interested in...' and instead create an engaging start that reflects your unique journey.",
      highlight: true,
    },
    {
      question: "Should I include my research experience in my SOP?",
      answer:
        "Absolutely! Research experience is highly valuable and should be prominently featured in your SOP. Describe your research projects, methodologies used, key findings, and what you learned from the experience. Explain how this research sparked your interest in the field and how it relates to your future academic goals. Even undergraduate research projects can demonstrate your commitment and analytical skills.",
    },
    {
      question: "How do I connect my past experiences to my future goals?",
      answer:
        "Create a logical narrative that shows progression from your past experiences to your current interests and future aspirations. Explain how each experience - academic, professional, or personal - contributed to your understanding of the field and shaped your career goals. Use transition phrases to show cause-and-effect relationships and demonstrate that your decision to pursue this program is well-thought-out and purposeful.",
    },
    {
      question:
        "What if I'm changing fields - how do I address this in my SOP?",
      answer:
        "If you're transitioning to a new field, clearly explain your motivation for the change and how your previous experience provides transferable skills. Highlight relevant coursework, projects, or experiences that demonstrate your commitment to the new field. Show that you've thought carefully about this transition and have taken steps to prepare for it, such as additional courses, certifications, or relevant projects.",
    },
    {
      question: "How many drafts should I write before submitting my SOP?",
      answer:
        "Plan to write multiple drafts - typically 5-8 revisions are normal for a strong SOP. Start with a rough outline, then expand into a first draft focusing on content. Subsequent drafts should refine structure, clarity, and flow. Have trusted mentors, professors, or professionals review your drafts and provide feedback. The final draft should be polished, error-free, and compelling. Allow several weeks for this iterative process.",
    },
    
    {
      question: "Can you prepare Letters of Recommendation as well?",
      answer:
        "Absolutely. If you’ve booked an SOP with us, LOR drafts come at a discounted rate. Tell our counsellor your needs, and we’ll quote the discounted fee.",
    },
    {
      question: "Do you write Visa SOPs? (No - We create only Admission SOPs)",
      answer:
        "No. We do not create Visa SOPs or visa cover letters. Our service is only for university admission Statements of Purpose (Admission SOPs) only.",
    },
    {
      question: "What happens if my payment fails but the amount is deducted?",
      answer:
        "Any debited amount is automatically refunded within 3–7 business days.",
    },
    {
      question:
        "When will I get my SOP draft? I need more than 1 SOP, do I get a discount?",
      answer:
        "We will send you the first draft within 1-2 business days of payment confirmation. Tight deadline or ordering more than three SOPs? Mention it in that initial conversation and our editor will confirm the feasibility.",
    },
  ];

  // Helper: splits array into two columns by even/odd index for alignment
  function splitToAlternatingColumns(arr) {
    const left = [];
    const right = [];
    arr.forEach((item, i) => {
      if (i % 2 === 0) {
        left.push(item);
      } else {
        right.push(item);
      }
    });
    return [left, right];
  }

  // Default: first 10 questions in 2 columns
  const [defaultLeftFAQs, defaultRightFAQs] = splitToAlternatingColumns(
    faqs.slice(0, 10)
  );
  // Show All: all questions in 2 columns
  const [allLeftFAQs, allRightFAQs] = splitToAlternatingColumns(faqs);

  return (
    <section
      id="faq"
      className="py-14 px-4 bg-gradient-to-br from-[hsl(var(--hero-gradient-start))] to-[hsl(var(--hero-gradient-end))] relative"
    >
      <div className="container-app mx-auto relative z-10">
        {/* TITLE BLOCK */}
        <div className="text-center mb-16">
          <h2 className="font-heading text-3xl sm:text-4xl lg:text-5xl font-bold text-foreground mb-4">
            Frequently Asked <span className="text-primary">Questions</span>
          </h2>

          <p className="font-body text-lg text-muted-foreground max-w-3xl mx-auto">
            Everything you need to know about creating a compelling Statement of
            Purpose that stands out.
          </p>
        </div>

        {/* FAQ GRID */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-x-10 gap-y-6">
          {/* LEFT SIDE */}
          <div className="space-y-6">
            {(showAll ? allLeftFAQs : defaultLeftFAQs).map((faq) => {
              const questionIndex = faqs.indexOf(faq);

              return (
                <Card
                  key={questionIndex}
                  className={`w-full border border-muted bg-card shadow-md hover:shadow-lg transition-all duration-200 ${
                    faq.highlight
                      ? "border-l-4 border-l-primary bg-primary/-5"
                      : ""
                  }`}
                >
                  <CardContent className="p-0">
                    {/* Question Button */}
                    <button
                      onClick={() => toggleItem(questionIndex)}
                      className="w-full px-8 py-6 text-left rounded-lg focus:outline-none"
                    >
                      <div className="flex items-center justify-between">
                        <h3
                          className={`font-heading font-semibold text-lg text-foreground pr-4 ${
                            faq.highlight ? "text-primary" : ""
                          }`}
                        >
                          {faq.question}

                          {faq.highlight && (
                            <span className="inline-flex items-center ml-2 px-2 py-1 text-xs font-medium bg-primary text-primary-foreground rounded-full">
                              Important
                            </span>
                          )}
                        </h3>

                        <div className="flex-shrink-0">
                          {openItems.includes(questionIndex) ? (
                            <Minus className="h-5 w-5 text-primary" />
                          ) : (
                            <Plus className="h-5 w-5 text-primary" />
                          )}
                        </div>
                      </div>
                    </button>

                    {/* Answer */}
                    {openItems.includes(questionIndex) && (
                      <div className="px-8 pb-6">
                        <div className="pt-4 border-t border-muted">
                          <p className="font-body text-muted-foreground leading-relaxed">
                            {faq.answer}
                          </p>
                        </div>
                      </div>
                    )}
                  </CardContent>
                </Card>
              );
            })}
          </div>

          {/* RIGHT SIDE */}
          <div className="space-y-6">
            {(showAll ? allRightFAQs : defaultRightFAQs).map((faq) => {
              const questionIndex = faqs.indexOf(faq);

              return (
                <Card
                  key={questionIndex}
                  className={`w-full border border-muted bg-card shadow-md hover:shadow-lg transition-all duration-200 ${
                    faq.highlight
                      ? "border-l-4 border-l-primary bg-primary/5"
                      : ""
                  }`}
                >
                  <CardContent className="p-0">
                    {/* Question Button */}
                    <button
                      onClick={() => toggleItem(questionIndex)}
                      className="w-full px-8 py-6 text-left rounded-lg focus:outline-none"
                    >
                      <div className="flex items-center justify-between">
                        <h3
                          className={`font-heading font-semibold text-lg text-foreground pr-4 ${
                            faq.highlight ? "text-primary" : ""
                          }`}
                        >
                          {faq.question}

                          {faq.highlight && (
                            <span className="inline-flex items-center ml-2 px-2 py-1 text-xs font-medium bg-primary text-primary-foreground rounded-full">
                              Important
                            </span>
                          )}
                        </h3>

                        <div className="flex-shrink-0">
                          {openItems.includes(questionIndex) ? (
                            <Minus className="h-5 w-5 text-primary" />
                          ) : (
                            <Plus className="h-5 w-5 text-primary" />
                          )}
                        </div>
                      </div>
                    </button>

                    {/* Answer */}
                    {openItems.includes(questionIndex) && (
                      <div className="px-8 pb-6">
                        <div className="pt-4 border-t border-muted">
                          <p className="font-body text-muted-foreground leading-relaxed">
                            {faq.answer}
                          </p>
                        </div>
                      </div>
                    )}
                  </CardContent>
                </Card>
              );
            })}
          </div>
        </div>

        {/* VIEW MORE BUTTON */}
        {faqs.length > 10 && (
          <div className="mt-10 text-center">
            <button
              className="bg-primary hover:bg-primary/90 text-primary-foreground px-8 py-3 rounded-lg font-heading font-semibold transition-colors"
              onClick={() => setShowAll((prev) => !prev)}
            >
              {showAll ? "View Less" : "View More"}
            </button>
          </div>
        )}
      </div>
    </section>
  );
};

export default FAQSection;
